name: Reusable workflow example

on:
  push:
    branches-ignore:
        main

  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
    build:
        runs-on: windows-latest
        timeout-minutes: 15
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3.4.0
            
            - name: Output Readme
              shell: pwsh
              run: |  
                   Write-Output "# ${{ inputs.version }}" >> $env:GITHUB_STEP_SUMMARY     
                   Write-Output "# build.yml" >> $env:GITHUB_STEP_SUMMARY
                   Get-Content "README.md" >> $env:GITHUB_STEP_SUMMARY
         
