name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
    build:
        runs-on: windows-latest
        timeout-minutes: 15
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3.4.0
            
            - name: Output Readme
              id: modelcheck
              shell: pwsh
              run: |          
                   Write-Output "# build.yml" >> $env:GITHUB_STEP_SUMMARY
                   Get-Content "README.md" >> $env:GITHUB_STEP_SUMMARY
         
