name: Push on main 
env: 
    Version: $ProductVersion
on:
    push:
      branches:
        - main
jobs:
    
    call-workflow-passing-data:
        uses: ./.github/workflows/build.yml
        with:
            version: $Version
        secrets: inherit
    
      