name: Push on main 

on:
    push:
      branches:
        - main
jobs:
    
    call-workflow-passing-data:
       
        uses: ./.github/workflows/build.yml
        with:
            version: '${{env.ProductVersion}}'
        secrets: inherit
    
      