name: Push on main 
on:
    push:
      branches:
        - main
jobs:
    
    call-workflow-passing-data:
        uses: ./.github/workflows/build.yml
        with:
            config-path: .github/labeler.yml
        secrets: inherit
    
      