name: Push of Tag 
on:
    release:

jobs:
    prepareVersion:
        runs-on: windows-latest
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0 # Mandatory to use the extract version from tag action
        
            - name: Extract version from tag
              id: tagversion
              uses: damienaicheh/extract-version-from-tag-action@v1.1.0
            
            - name: Output Readme
              shell: pwsh
              run: |          
                    
                    Write-Output "# release.yml" >> $env:GITHUB_STEP_SUMMARY
                    Write-Output "${{ steps.tagversion.outputs.MAJOR }}" >> $env:GITHUB_STEP_SUMMARY
                    Write-Output "# release.yml" >> $env:GITHUB_STEP_SUMMARY
                    Get-Content "README.md" >> $env:GITHUB_STEP_SUMMARY
              
    build:
        uses: ./.github/workflows/build.yml
        needs: prepareVersion
        with:
            config-path: .github/labeler.yml
        secrets: inherit
