name: Push of Tag 

env: 
    Version: "0.0.0"

on:
    release:
      types: [created]

jobs:
    prepareVersion:
        runs-on: windows-latest
        timeout-minutes: 15
        outputs:
            versionString: ${{ steps.get_version.outputs.version-without-v }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0 # Mandatory to use the extract version from tag action
        
            - name: Extract version from tag
              id: get_version
              uses: battila7/get-version-action@v2

            - name: Output Readme
              shell: pwsh
              run: |       
                    Write-Output "# release.yml" >> $env:GITHUB_STEP_SUMMARY
                    Write-Output "# ${{ steps.get_version.outputs.version-without-v }}" >> $env:GITHUB_STEP_SUMMARY
                    

    outputVersion:
        needs: prepareVersion
        runs-on: windows-latest
        timeout-minutes: 15
        steps:
            - name: Output Version
              shell: pwsh
              run: |    
                    Write-Output "# release.yml" >> $env:GITHUB_STEP_SUMMARY
                    Write-Output "# Version: ${{needs.prepareVersion.outputs.versionString}}" >> $env:GITHUB_STEP_SUMMARY            
                    
        
    build:
        uses: ./.github/workflows/build.yml
        needs: prepareVersion
        with:
            version: ${{needs.prepareVersion.outputs.versionString}}
        secrets: inherit
