name: Push of Tag 
on:
    release:
      types: [created]

jobs:
    prepareVersion:
        runs-on: windows-latest
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0 # Mandatory to use the extract version from tag action
        
            - name: Extract version from tag
              id: get_version
              uses: battila7/get-version-action@v2
            
            - name: Output Readme
              shell: pwsh
              run: |          
                    
                    Write-Output "# release.yml" >> $env:GITHUB_STEP_SUMMARY
                    Write-Output "# ${{ steps.get_version.outputs.version-without-v }}" >> $env:GITHUB_STEP_SUMMARY
                    Write-Output "# ${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}" >> $env:GITHUB_STEP_SUMMARY
                    
                    Write-Output "# release.yml" >> $env:GITHUB_STEP_SUMMARY
                    Get-Content "README.md" >> $env:GITHUB_STEP_SUMMARY

            
              
            
              
    build:
        uses: ./.github/workflows/build.yml
        needs: prepareVersion
        with:
            config-path: .github/labeler.yml
        secrets: inherit
